[package]
name = "guacamole"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.27.5"
env_logger = "0.9.3"
log = "0.4.17"
wgpu = "0.14"
pollster = "0.2"
bytemuck = { version = "1.12", features = [ "derive" ] }
bevy_ecs = "0.9"
rand = "*"
glam = "0.22"
uuid = "1.2"
image = { version = "0.24.5", default-features = false, features = ["png", "jpeg"] }
encase = { version = "0.4", features = ["glam"] }
