name: CI

on:
  push:
  pull_request:

jobs:
  build-bundled:
    name: build bundled
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        feature: ["", "static-link"]
        build_mode: ["", "--release"]
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build SDL2
        shell: bash
        env:
          CI_BUILD_FEATURES: "bundled"
          RUST_TEST_THREADS: 1
        run: |
          set -xeuo pipefail
          rustc --version
          cargo --version
          cargo build --features "${CI_BUILD_FEATURES} ${{matrix.feature}}" ${{matrix.build_mode}}
          cargo build --examples --features "${CI_BUILD_FEATURES} ${{matrix.feature}}" ${{matrix.build_mode}}
